config/routes.rb
Rails.application.routes.draw do

  root 'poems#new'

  resources :poems, :only => [:new, :create, :show]

end

app/models/poem.rb
class Poem
  attr_reader :topic, :raw_text

  DEFAULT_POEMS = {
    :haiku => "Sorry, there are not\nEnough tweets about that word\nTry another one\n"
  }

  SYLLABLE_PATTERNS = {
    :haiku => [5, 7, 5]
  }

  def initialize(topic, raw_text)
    @topic = topic
    @service = PoemService.new(raw_text)
    @raw_text = raw_text
  end

  def to_haiku
    _to_type(:haiku)
  end

  def _to_type(type)
    return DEFAULT_POEMS[type] unless @raw_text.present?

    lines = _build_lines_for(type)

    return DEFAULT_POEMS[type] unless _has_enough_lines(type, lines)

    _output(lines)
  end

  def _build_lines_for(type)
    SYLLABLE_PATTERNS[type].map do |syllables_per_line|
      @service.get_syllables(syllables_per_line)
    end.compact
  end

  def _has_enough_lines(type, lines)
    lines.length == SYLLABLE_PATTERNS[type].length
  end

  def _output(lines)
    lines.map(&:humanize).join("\n")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  rescue_from Twitter::Error, with: :bad_request
  rescue_from Twitter::Error::Forbidden, with: :bad_request
  rescue_from Twitter::Error::BadRequest, with: :bad_request
  rescue_from Twitter::Error::TooManyRequests, with: :too_many_requests
  rescue_from Twitter::Error::Unauthorized, with: :unauthorized

  def create
    results = TwitterService.text_from_query(params[:query])

    if results
      @poem = Poem.new(params[:query], results)
      render :show, :status => :created
    else
      redirect_to :new_poem
    end
  end

  def new
    @trending_topics = TwitterService.trending_topics
  end

  private

  def bad_request
    flash[:error] = TwitterService::BAD_REQUEST_MESSAGE
    render 'error'
  end

  def too_many_requests
    flash[:error] = TwitterService::RATE_LIMIT_ERROR_MESSAGE
    render 'error'
  end

  def unauthorized 
    flash[:error] = TwitterService::UNAUTHORIZED_MESSAGE
    redirect_to :new_poem
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterPoems</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poems/error.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <h3 class="alert alert-<%= key %>"><%= value %></h3>
  <% end %>
</div>

app/views/poems/new.html.erb
<h1>Twitter Poem Generator</h1>
<p>You know when you're in the mood for a haiku but can't come up with the words yourself? Let twitter help!</p>

<%= form_tag("/poems", method: "post") do %>
  <%= label_tag(:query, "Enter a word for the topic of the poem:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Create your poem") %>
<% end %>

<% unless @trending_topics.empty? %>
  <p>(If you need ideas, the following are popular topics trending on twitter now...)</p>
  <ul>
    <% @trending_topics.each do |topic| %>
    <li><%= topic %></li>
    <% end %>
  </ul>
<% end %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>
<h1>A haiku about <%=@poem.topic %></h1>
<p>
  <%= simple_format(@poem.to_haiku) %>
</p>

<%= button_to 'Back', new_poem_path, method: :get  %>